<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `drupal`
//

// `drupal`.`role_permission`
$role_permission = array(
  array('rid' => '1','permission' => 'access comments','module' => 'comment'),
  array('rid' => '1','permission' => 'access content','module' => 'node'),
  array('rid' => '1','permission' => 'access er content','module' => 'er'),
  array('rid' => '1','permission' => 'create field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '1','permission' => 'search content','module' => 'search'),
  array('rid' => '1','permission' => 'use advanced search','module' => 'search'),
  array('rid' => '1','permission' => 'use text format filtered_html','module' => 'filter'),
  array('rid' => '1','permission' => 'view own field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '2','permission' => 'access comments','module' => 'comment'),
  array('rid' => '2','permission' => 'access er content','module' => 'er'),
  array('rid' => '2','permission' => 'access user profiles','module' => 'user'),
  array('rid' => '2','permission' => 'edit own field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '2','permission' => 'edit own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '2','permission' => 'edit own main profile','module' => 'profile2'),
  array('rid' => '2','permission' => 'post comments','module' => 'comment'),
  array('rid' => '2','permission' => 'search content','module' => 'search'),
  array('rid' => '2','permission' => 'use advanced search','module' => 'search'),
  array('rid' => '2','permission' => 'use text format filtered_html','module' => 'filter'),
  array('rid' => '2','permission' => 'view any administrative_staff profile','module' => 'profile2'),
  array('rid' => '2','permission' => 'view any administrator profile','module' => 'profile2'),
  array('rid' => '2','permission' => 'view any student profile','module' => 'profile2'),
  array('rid' => '2','permission' => 'view own field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '2','permission' => 'view own main profile','module' => 'profile2'),
  array('rid' => '2','permission' => 'view own student profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'access administration menu','module' => 'admin_menu'),
  array('rid' => '3','permission' => 'access administration pages','module' => 'system'),
  array('rid' => '3','permission' => 'access all views','module' => 'views'),
  array('rid' => '3','permission' => 'access backup and migrate','module' => 'backup_migrate'),
  array('rid' => '3','permission' => 'access backup files','module' => 'backup_migrate'),
  array('rid' => '3','permission' => 'access comments','module' => 'comment'),
  array('rid' => '3','permission' => 'access content','module' => 'node'),
  array('rid' => '3','permission' => 'access content overview','module' => 'node'),
  array('rid' => '3','permission' => 'access contextual links','module' => 'contextual'),
  array('rid' => '3','permission' => 'access dashboard','module' => 'dashboard'),
  array('rid' => '3','permission' => 'access devel information','module' => 'devel'),
  array('rid' => '3','permission' => 'access er content','module' => 'er'),
  array('rid' => '3','permission' => 'access private fields','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'access rules debug','module' => 'rules'),
  array('rid' => '3','permission' => 'access site in maintenance mode','module' => 'system'),
  array('rid' => '3','permission' => 'access site reports','module' => 'system'),
  array('rid' => '3','permission' => 'access user profiles','module' => 'user'),
  array('rid' => '3','permission' => 'administer actions','module' => 'system'),
  array('rid' => '3','permission' => 'administer advanced pane settings','module' => 'panels'),
  array('rid' => '3','permission' => 'administer backup and migrate','module' => 'backup_migrate'),
  array('rid' => '3','permission' => 'administer blocks','module' => 'block'),
  array('rid' => '3','permission' => 'administer comments','module' => 'comment'),
  array('rid' => '3','permission' => 'administer content types','module' => 'node'),
  array('rid' => '3','permission' => 'administer encrypt','module' => 'encrypt'),
  array('rid' => '3','permission' => 'administer er','module' => 'er'),
  array('rid' => '3','permission' => 'administer features','module' => 'features'),
  array('rid' => '3','permission' => 'administer field permissions','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'administer fieldgroups','module' => 'field_group'),
  array('rid' => '3','permission' => 'administer filters','module' => 'filter'),
  array('rid' => '3','permission' => 'administer flags','module' => 'flag'),
  array('rid' => '3','permission' => 'administer image styles','module' => 'image'),
  array('rid' => '3','permission' => 'administer menu','module' => 'menu'),
  array('rid' => '3','permission' => 'administer modules','module' => 'system'),
  array('rid' => '3','permission' => 'administer nodes','module' => 'node'),
  array('rid' => '3','permission' => 'administer page manager','module' => 'page_manager'),
  array('rid' => '3','permission' => 'administer pane access','module' => 'panels'),
  array('rid' => '3','permission' => 'administer panels layouts','module' => 'panels'),
  array('rid' => '3','permission' => 'administer panels styles','module' => 'panels'),
  array('rid' => '3','permission' => 'administer pcp','module' => 'pcp'),
  array('rid' => '3','permission' => 'administer permissions','module' => 'user'),
  array('rid' => '3','permission' => 'administer profile types','module' => 'profile2'),
  array('rid' => '3','permission' => 'administer profile2_regpath','module' => 'profile2_regpath'),
  array('rid' => '3','permission' => 'administer profiles','module' => 'profile2'),
  array('rid' => '3','permission' => 'administer rules','module' => 'rules'),
  array('rid' => '3','permission' => 'administer search','module' => 'search'),
  array('rid' => '3','permission' => 'administer shortcuts','module' => 'shortcut'),
  array('rid' => '3','permission' => 'administer site configuration','module' => 'system'),
  array('rid' => '3','permission' => 'administer software updates','module' => 'system'),
  array('rid' => '3','permission' => 'administer taxonomy','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'administer themes','module' => 'system'),
  array('rid' => '3','permission' => 'administer url aliases','module' => 'path'),
  array('rid' => '3','permission' => 'administer users','module' => 'user'),
  array('rid' => '3','permission' => 'administer views','module' => 'views'),
  array('rid' => '3','permission' => 'block IP addresses','module' => 'system'),
  array('rid' => '3','permission' => 'bypass node access','module' => 'node'),
  array('rid' => '3','permission' => 'bypass rules access','module' => 'rules'),
  array('rid' => '3','permission' => 'cancel account','module' => 'user'),
  array('rid' => '3','permission' => 'cancel users with no custom roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role administrativestaff','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role administrativestaff and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role administrator','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role administrator and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role anonymoususer','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role anonymoususer and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role authenticateduser','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role authenticateduser and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role faculty','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role faculty and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role student','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'cancel users with role student and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'change layouts in place editing','module' => 'panels'),
  array('rid' => '3','permission' => 'change own username','module' => 'user'),
  array('rid' => '3','permission' => 'create article content','module' => 'node'),
  array('rid' => '3','permission' => 'create blog content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_award content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_book content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_collaboration content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_collaborators content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_effort content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_engagement content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_event content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_institution content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_internet content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_news content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_nsf_fastlane content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_other_product content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_paid content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_patent content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_poster content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_presentation content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_proposal content','module' => 'node'),
  array('rid' => '3','permission' => 'create er_publication content','module' => 'node'),
  array('rid' => '3','permission' => 'create field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'create field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'create group content','module' => 'node'),
  array('rid' => '3','permission' => 'create image_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'create node_gallery_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'create node_gallery_image content','module' => 'node'),
  array('rid' => '3','permission' => 'create page content','module' => 'node'),
  array('rid' => '3','permission' => 'create post content','module' => 'node'),
  array('rid' => '3','permission' => 'create url aliases','module' => 'path'),
  array('rid' => '3','permission' => 'create users','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'create webform content','module' => 'node'),
  array('rid' => '3','permission' => 'customize shortcut links','module' => 'shortcut'),
  array('rid' => '3','permission' => 'delete any article content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any blog content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_award content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_book content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_collaboration content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_collaborators content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_effort content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_engagement content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_event content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_institution content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_internet content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_news content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_nsf_fastlane content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_other_product content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_paid content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_patent content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_poster content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_presentation content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_proposal content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any er_publication content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any group content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any image_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any node_gallery_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any node_gallery_image content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any page content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any post content','module' => 'node'),
  array('rid' => '3','permission' => 'delete any webform content','module' => 'node'),
  array('rid' => '3','permission' => 'delete backup files','module' => 'backup_migrate'),
  array('rid' => '3','permission' => 'delete own article content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own blog content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_award content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_book content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_collaboration content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_collaborators content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_effort content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_engagement content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_event content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_institution content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_internet content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_news content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_nsf_fastlane content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_other_product content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_paid content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_patent content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_poster content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_presentation content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_proposal content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own er_publication content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own group content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own image_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own node_gallery_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own node_gallery_image content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own page content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own post content','module' => 'node'),
  array('rid' => '3','permission' => 'delete own webform content','module' => 'node'),
  array('rid' => '3','permission' => 'delete revisions','module' => 'node'),
  array('rid' => '3','permission' => 'delete terms in 1','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'delete terms in 2','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'delete terms in 3','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'delete terms in 4','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'display drupal links','module' => 'admin_menu'),
  array('rid' => '3','permission' => 'download er content','module' => 'er'),
  array('rid' => '3','permission' => 'edit any administrative_staff profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit any administrator profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit any article content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any blog content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_award content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_book content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_collaboration content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_collaborators content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_effort content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_engagement content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_event content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_institution content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_internet content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_news content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_nsf_fastlane content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_other_product content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_paid content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_patent content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_poster content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_presentation content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_proposal content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any er_publication content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any faculty profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit any group content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any image_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any main profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit any node_gallery_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any node_gallery_image content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any page content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any post content','module' => 'node'),
  array('rid' => '3','permission' => 'edit any student profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit any webform content','module' => 'node'),
  array('rid' => '3','permission' => 'edit field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'edit field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'edit own administrative_staff profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit own administrator profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit own article content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own blog content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own comments','module' => 'comment'),
  array('rid' => '3','permission' => 'edit own er_award content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_book content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_collaboration content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_collaborators content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_effort content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_engagement content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_event content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_institution content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_internet content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_news content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_nsf_fastlane content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_other_product content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_paid content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_patent content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_poster content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_presentation content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_proposal content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own er_publication content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own faculty profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit own field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'edit own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'edit own group content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own image_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own main profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit own node_gallery_gallery content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own node_gallery_image content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own page content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own post content','module' => 'node'),
  array('rid' => '3','permission' => 'edit own student profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'edit own webform content','module' => 'node'),
  array('rid' => '3','permission' => 'edit terms in 1','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'edit terms in 2','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'edit terms in 3','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'edit terms in 4','module' => 'taxonomy'),
  array('rid' => '3','permission' => 'edit users with no custom roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role administrativestaff','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role administrativestaff and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role administrator','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role administrator and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role anonymoususer','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role anonymoususer and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role authenticateduser','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role authenticateduser and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role faculty','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role faculty and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role student','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'edit users with role student and other roles','module' => 'administerusersbyrole'),
  array('rid' => '3','permission' => 'execute php code','module' => 'devel'),
  array('rid' => '3','permission' => 'flush caches','module' => 'admin_menu'),
  array('rid' => '3','permission' => 'manage features','module' => 'features'),
  array('rid' => '3','permission' => 'perform backup','module' => 'backup_migrate'),
  array('rid' => '3','permission' => 'post comments','module' => 'comment'),
  array('rid' => '3','permission' => 'restore from backup','module' => 'backup_migrate'),
  array('rid' => '3','permission' => 'revert revisions','module' => 'node'),
  array('rid' => '3','permission' => 'search content','module' => 'search'),
  array('rid' => '3','permission' => 'select account cancellation method','module' => 'user'),
  array('rid' => '3','permission' => 'skip comment approval','module' => 'comment'),
  array('rid' => '3','permission' => 'switch shortcut sets','module' => 'shortcut'),
  array('rid' => '3','permission' => 'switch users','module' => 'devel'),
  array('rid' => '3','permission' => 'use advanced search','module' => 'search'),
  array('rid' => '3','permission' => 'use flag import','module' => 'flag'),
  array('rid' => '3','permission' => 'use page manager','module' => 'page_manager'),
  array('rid' => '3','permission' => 'use panels caching features','module' => 'panels'),
  array('rid' => '3','permission' => 'use panels dashboard','module' => 'panels'),
  array('rid' => '3','permission' => 'use panels in place editing','module' => 'panels'),
  array('rid' => '3','permission' => 'use panels locks','module' => 'panels'),
  array('rid' => '3','permission' => 'use PHP for settings','module' => 'php'),
  array('rid' => '3','permission' => 'use text format filtered_html','module' => 'filter'),
  array('rid' => '3','permission' => 'use text format full_html','module' => 'filter'),
  array('rid' => '3','permission' => 'use text format php_code','module' => 'filter'),
  array('rid' => '3','permission' => 'view any administrative_staff profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view any administrator profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view any faculty profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view any main profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view any student profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view date repeats','module' => 'date_repeat_field'),
  array('rid' => '3','permission' => 'view field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'view field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'view own administrative_staff profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view own administrator profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view own faculty profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view own field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'view own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '3','permission' => 'view own main profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view own student profile','module' => 'profile2'),
  array('rid' => '3','permission' => 'view own unpublished content','module' => 'node'),
  array('rid' => '3','permission' => 'view pane admin links','module' => 'panels'),
  array('rid' => '3','permission' => 'view revisions','module' => 'node'),
  array('rid' => '3','permission' => 'view the administration theme','module' => 'system'),
  array('rid' => '66784200','permission' => 'access administration menu','module' => 'admin_menu'),
  array('rid' => '66784200','permission' => 'access administration pages','module' => 'system'),
  array('rid' => '66784200','permission' => 'access comments','module' => 'comment'),
  array('rid' => '66784200','permission' => 'access content overview','module' => 'node'),
  array('rid' => '66784200','permission' => 'access er content','module' => 'er'),
  array('rid' => '66784200','permission' => 'access user profiles','module' => 'user'),
  array('rid' => '66784200','permission' => 'change own username','module' => 'user'),
  array('rid' => '66784200','permission' => 'create article content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create blog content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_award content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_book content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_collaboration content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_effort content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_engagement content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_event content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_institution content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_internet content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_news content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_nsf_fastlane content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_other_product content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_paid content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_patent content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_poster content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_presentation content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_proposal content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create er_publication content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '66784200','permission' => 'create group content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create image_gallery content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create node_gallery_gallery content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create node_gallery_image content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create page content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create post content','module' => 'node'),
  array('rid' => '66784200','permission' => 'create webform content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own article content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own blog content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_award content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_book content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_collaboration content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_effort content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_engagement content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_event content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_institution content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_internet content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_news content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_nsf_fastlane content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_other_product content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_paid content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_patent content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_poster content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_presentation content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_proposal content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own er_publication content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own image_gallery content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own node_gallery_gallery content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own node_gallery_image content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own page content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own post content','module' => 'node'),
  array('rid' => '66784200','permission' => 'delete own webform content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own article content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own blog content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own comments','module' => 'comment'),
  array('rid' => '66784200','permission' => 'edit own er_award content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_book content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_collaboration content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_effort content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_engagement content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_event content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_institution content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_internet content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_news content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_nsf_fastlane content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_other_product content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_paid content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_patent content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_poster content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_presentation content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_proposal content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own er_publication content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '66784200','permission' => 'edit own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '66784200','permission' => 'edit own group content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own image_gallery content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own node_gallery_gallery content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own node_gallery_image content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own page content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own post content','module' => 'node'),
  array('rid' => '66784200','permission' => 'edit own student profile','module' => 'profile2'),
  array('rid' => '66784200','permission' => 'edit own webform content','module' => 'node'),
  array('rid' => '66784200','permission' => 'post comments','module' => 'comment'),
  array('rid' => '66784200','permission' => 'search content','module' => 'search'),
  array('rid' => '66784200','permission' => 'use advanced search','module' => 'search'),
  array('rid' => '66784200','permission' => 'use text format filtered_html','module' => 'filter'),
  array('rid' => '66784200','permission' => 'view any student profile','module' => 'profile2'),
  array('rid' => '66784200','permission' => 'view date repeats','module' => 'date_repeat_field'),
  array('rid' => '66784200','permission' => 'view own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '66784200','permission' => 'view own student profile','module' => 'profile2'),
  array('rid' => '66784200','permission' => 'view own unpublished content','module' => 'node'),
  array('rid' => '137756511','permission' => 'access administration menu','module' => 'admin_menu'),
  array('rid' => '137756511','permission' => 'access administration pages','module' => 'system'),
  array('rid' => '137756511','permission' => 'access comments','module' => 'comment'),
  array('rid' => '137756511','permission' => 'access content overview','module' => 'node'),
  array('rid' => '137756511','permission' => 'access er content','module' => 'er'),
  array('rid' => '137756511','permission' => 'access user profiles','module' => 'user'),
  array('rid' => '137756511','permission' => 'change own username','module' => 'user'),
  array('rid' => '137756511','permission' => 'create article content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create blog content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_award content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_book content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_collaboration content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_effort content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_engagement content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_event content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_institution content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_internet content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_news content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_nsf_fastlane content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_other_product content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_paid content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_patent content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_poster content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_presentation content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_proposal content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create er_publication content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '137756511','permission' => 'create group content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create image_gallery content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create node_gallery_gallery content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create node_gallery_image content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create page content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create post content','module' => 'node'),
  array('rid' => '137756511','permission' => 'create webform content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own article content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own blog content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_award content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_book content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_collaboration content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_effort content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_engagement content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_event content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_institution content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_internet content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_news content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_nsf_fastlane content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_other_product content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_paid content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_patent content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_poster content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_presentation content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_proposal content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own er_publication content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own image_gallery content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own node_gallery_gallery content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own node_gallery_image content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own page content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own post content','module' => 'node'),
  array('rid' => '137756511','permission' => 'delete own webform content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '137756511','permission' => 'edit own article content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own blog content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own comments','module' => 'comment'),
  array('rid' => '137756511','permission' => 'edit own er_award content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_book content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_collaboration content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_effort content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_engagement content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_event content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_institution content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_internet content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_news content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_nsf_fastlane content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_other_product content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_paid content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_patent content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_poster content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_presentation content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_proposal content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own er_publication content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '137756511','permission' => 'edit own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '137756511','permission' => 'edit own group content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own image_gallery content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own node_gallery_gallery content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own node_gallery_image content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own page content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own post content','module' => 'node'),
  array('rid' => '137756511','permission' => 'edit own student profile','module' => 'profile2'),
  array('rid' => '137756511','permission' => 'edit own webform content','module' => 'node'),
  array('rid' => '137756511','permission' => 'post comments','module' => 'comment'),
  array('rid' => '137756511','permission' => 'search content','module' => 'search'),
  array('rid' => '137756511','permission' => 'use advanced search','module' => 'search'),
  array('rid' => '137756511','permission' => 'use text format filtered_html','module' => 'filter'),
  array('rid' => '137756511','permission' => 'view any student profile','module' => 'profile2'),
  array('rid' => '137756511','permission' => 'view date repeats','module' => 'date_repeat_field'),
  array('rid' => '137756511','permission' => 'view own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '137756511','permission' => 'view own unpublished content','module' => 'node'),
  array('rid' => '166149871','permission' => 'access administration menu','module' => 'admin_menu'),
  array('rid' => '166149871','permission' => 'access administration pages','module' => 'system'),
  array('rid' => '166149871','permission' => 'access content','module' => 'node'),
  array('rid' => '166149871','permission' => 'access content overview','module' => 'node'),
  array('rid' => '166149871','permission' => 'access er content','module' => 'er'),
  array('rid' => '166149871','permission' => 'access private fields','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'access user profiles','module' => 'user'),
  array('rid' => '166149871','permission' => 'administer comments','module' => 'comment'),
  array('rid' => '166149871','permission' => 'administer nodes','module' => 'node'),
  array('rid' => '166149871','permission' => 'administer profiles','module' => 'profile2'),
  array('rid' => '166149871','permission' => 'administer users','module' => 'user'),
  array('rid' => '166149871','permission' => 'bypass node access','module' => 'node'),
  array('rid' => '166149871','permission' => 'cancel users with no custom roles','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'cancel users with role faculty','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'cancel users with role faculty and other roles','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'cancel users with role student','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'cancel users with role student and other roles','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'change own username','module' => 'user'),
  array('rid' => '166149871','permission' => 'create article content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create blog content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_award content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_book content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_collaboration content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_collaborators content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_effort content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_engagement content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_event content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_institution content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_internet content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_news content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_nsf_fastlane content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_other_product content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_paid content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_patent content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_poster content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_presentation content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_proposal content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create er_publication content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'create group content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create image_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create node_gallery_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create node_gallery_image content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create page content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create post content','module' => 'node'),
  array('rid' => '166149871','permission' => 'create users','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'create webform content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any article content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any blog content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_award content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_book content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_collaboration content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_collaborators content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_effort content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_engagement content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_event content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_institution content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_internet content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_news content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_nsf_fastlane content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_other_product content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_paid content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_patent content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_poster content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_presentation content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_proposal content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any er_publication content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any group content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any image_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any node_gallery_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any node_gallery_image content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any page content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any post content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete any webform content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own article content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own blog content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_award content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_book content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_collaboration content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_collaborators content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_effort content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_engagement content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_event content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_institution content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_internet content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_news content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_nsf_fastlane content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_other_product content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_paid content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_patent content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_poster content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_presentation content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_proposal content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own er_publication content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own group content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own image_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own node_gallery_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own node_gallery_image content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own page content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own post content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete own webform content','module' => 'node'),
  array('rid' => '166149871','permission' => 'delete revisions','module' => 'node'),
  array('rid' => '166149871','permission' => 'download er content','module' => 'er'),
  array('rid' => '166149871','permission' => 'edit any administrative_staff profile','module' => 'profile2'),
  array('rid' => '166149871','permission' => 'edit any administrator profile','module' => 'profile2'),
  array('rid' => '166149871','permission' => 'edit any article content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any blog content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_award content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_book content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_collaboration content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_collaborators content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_effort content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_engagement content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_event content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_institution content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_internet content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_news content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_nsf_fastlane content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_other_product content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_paid content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_patent content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_poster content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_presentation content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_proposal content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any er_publication content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any group content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any image_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any node_gallery_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any node_gallery_image content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any page content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any post content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit any webform content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'edit field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'edit own administrative_staff profile','module' => 'profile2'),
  array('rid' => '166149871','permission' => 'edit own administrator profile','module' => 'profile2'),
  array('rid' => '166149871','permission' => 'edit own article content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own blog content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own comments','module' => 'comment'),
  array('rid' => '166149871','permission' => 'edit own er_award content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_book content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_collaboration content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_collaborators content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_effort content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_engagement content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_event content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_institution content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_internet content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_news content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_nsf_fastlane content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_other_product content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_paid content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_patent content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_poster content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_presentation content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_proposal content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own er_publication content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'edit own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'edit own group content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own image_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own node_gallery_gallery content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own node_gallery_image content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own page content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own post content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit own student profile','module' => 'profile2'),
  array('rid' => '166149871','permission' => 'edit own webform content','module' => 'node'),
  array('rid' => '166149871','permission' => 'edit users with no custom roles','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'edit users with role administrativestaff','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'edit users with role faculty','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'edit users with role faculty and other roles','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'edit users with role student','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'edit users with role student and other roles','module' => 'administerusersbyrole'),
  array('rid' => '166149871','permission' => 'flush caches','module' => 'admin_menu'),
  array('rid' => '166149871','permission' => 'revert revisions','module' => 'node'),
  array('rid' => '166149871','permission' => 'search content','module' => 'search'),
  array('rid' => '166149871','permission' => 'skip comment approval','module' => 'comment'),
  array('rid' => '166149871','permission' => 'use advanced search','module' => 'search'),
  array('rid' => '166149871','permission' => 'use text format full_html','module' => 'filter'),
  array('rid' => '166149871','permission' => 'view date repeats','module' => 'date_repeat_field'),
  array('rid' => '166149871','permission' => 'view field_er_disabilities','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'view field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'view own administrative_staff profile','module' => 'profile2'),
  array('rid' => '166149871','permission' => 'view own administrator profile','module' => 'profile2'),
  array('rid' => '166149871','permission' => 'view own field_er_phone_personal','module' => 'field_permissions'),
  array('rid' => '166149871','permission' => 'view own unpublished content','module' => 'node'),
  array('rid' => '166149871','permission' => 'view revisions','module' => 'node'),
  array('rid' => '166149871','permission' => 'view the administration theme','module' => 'system')
);
